#!/bin/bash
c=${0%/*}/config ; source "$c" ; if [ $? -ne 0 ] ; then echo "Error: no config file $c" 1>&2 ; exit 1 ; fi

#scan for directories
for DIR in $WEBSITES_DIR/*; do
    if [ -d "${DIR}" ]; then
	VHOST=${DIR##*/}
        printf "Checking ${VHOST} "
        if [ -f "${DIR}/logs/access.log" ]; then
	    echo " [ Have access log! ]"
	    CONFIG_FILE=${AWSTATS_CONFIG_DIR}/awstats.${VHOST}.conf
	    cp ${0%/*}/awstats.vhost.conf ${CONFIG_FILE}
	    sed -i -e s@"\$HOST"@$VHOST@g $CONFIG_FILE
	    if [ ! -d "${AWSTATS_DATA_DIR}/${VHOST}" ]; then
		mkdir ${AWSTATS_DATA_DIR}/${VHOST}
	    fi
	else
	    echo " [ NO LOG ]"
        fi
    fi
done
