#!/bin/bash
AWSTATS_DIR=/usr/local/etc/awstats
LANGUAGE=ru

#build pages
for FILE in $AWSTATS_DIR/*; do
    if [ -f "${FILE}" ]; then
	HOST=${FILE##*/}
	HOST=$(echo "$HOST" | sed 's/^awstats\.//g' | sed 's/\.conf$//g')
	if [ $HOST == "model" ]; then
	    continue
	fi
	echo " Pages for ${HOST} "
	echo $FILE
	awstats update now -output -staticlinks -config=${HOST} --lang=${LANGUAGE} > ${AWSTATS_DIR}/daata/${HOST}.html
    fi
done

#build list of pages
LIST=$AWSTATS_DIR/daata/list.html
echo "<h1>List</h1>" > $LIST
for FILE in $AWSTATS_DIR/*.html; do
    if [ -f "${FILE}" ]; then
	FILE=${FILE##*/}
	echo " <a href='${FILE}'>${FILE}</a> <br>" >> $LIST
    fi
done