#!/bin/bash
WEBSITES_DIR=/var/www/vhosts
AWSTATS_CONFIG_DIR=/var/www/awstats/config

#scan for directories
for DIR in $WEBSITES_DIR/*; do
    if [ -d "${DIR}" ]; then
	VHOST=${DIR##*/}
        printf "Checking ${VHOST} "
        if [ -f "${DIR}/logs/access.log" ]; then
	    echo " [ Log process! ]"
	    CONFIG_FILE=${AWSTATS_CONFIG_DIR}/awstats.${VHOST}.conf
	    cp ${0%/*}/awstats.vhost.conf ${CONFIG_FILE}
	    sed -i -e s@"\$HOST"@$VHOST@g $CONFIG_FILE
	    if [ ! -d "${AWSTATS_CONFIG_DIR}/../data/${VHOST}" ]; then
		mkdir ${AWSTATS_CONFIG_DIR}/../data/${VHOST}
	    fi
	else
	    echo " [ NO LOG ]"
        fi
    fi
done