#!/bin/bash
c=${0%/*}/config ; source "$c" ; if [ $? -ne 0 ] ; then echo "Error: no config file $c" 1>&2 ; exit 1 ; fi

#build pages
for FILE in $AWSTATS_DIR/*; do
    if [ -f "${FILE}" ]; then
	HOST=${FILE##*/}
	HOST=$(echo "$HOST" | sed 's/^awstats\.//g' | sed 's/\.conf$//g')
	if [ $HOST == "model" ]; then
	    continue
	fi
	echo " Pages for ${HOST} "
	echo $FILE
	${AWSTATS_BIN} update now -output -staticlinks -config=${HOST} --lang=${AWSTATS_LANG} > ${AWSTATS_DIR}/daata/${HOST}.html
    fi
done

#build list of pages
LIST=$AWSTATS_DIR/daata/list.html
echo "<h1>List</h1>" > $LIST
for FILE in $AWSTATS_DIR/*.html; do
    if [ -f "${FILE}" ]; then
	FILE=${FILE##*/}
	echo " <a href='${FILE}'>${FILE}</a> <br>" >> $LIST
    fi
done
